import { Gender, StudentStatus } from '@prisma/client';
export declare class CreateStudentDto {
    schoolYearId: string;
    classId: string;
    fullName?: string;
    familyAndMiddleName?: string;
    firstName?: string;
    dateOfBirth?: string;
    gender?: Gender;
    identifier?: string;
    ethnicity?: string;
    nationality?: string;
    address?: string;
    studentPhone?: string;
    previousSchool?: string;
    status?: StudentStatus;
    fatherName?: string;
    fatherPhone?: string;
    fatherJob?: string;
    fatherWorkplace?: string;
    motherName?: string;
    motherPhone?: string;
    motherJob?: string;
    motherWorkplace?: string;
    hasHealthInsurance?: boolean;
    healthInsuranceNumber?: string;
    healthInsuranceStartDate?: string;
    healthInsuranceEndDate?: string;
    healthInsuranceRegisteredHospital?: string;
    emergencyContactName?: string;
    emergencyContactRelationship?: string;
    emergencyContactPhone?: string;
    policyCategory?: string;
    bloodType?: string;
    allergy?: string;
    healthNotes?: string;
    notes?: string;
    customFields?: Record<string, string | string[]>;
}
