import { StudentsService } from './students.service';
import { CreateStudentDto } from './dto/create-student.dto';
import { UpdateStudentDto } from './dto/update-student.dto';
import { QueryStudentsDto } from './dto/query-students.dto';
import { ReorderStudentsDto } from './dto/reorder-students.dto';
import { BulkUpdateStudentsDto } from './dto/bulk-update-students.dto';
import { SeedDemoStudentsDto } from './dto/seed-demo-students.dto';
export declare class StudentsController {
    private readonly studentsService;
    constructor(studentsService: StudentsService);
    create(dto: CreateStudentDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        schoolYearId: string;
        classId: string;
        fullName: string | null;
        familyAndMiddleName: string | null;
        firstName: string | null;
        dateOfBirth: Date | null;
        gender: import(".prisma/client").$Enums.Gender | null;
        identifier: string | null;
        ethnicity: string | null;
        nationality: string | null;
        address: string | null;
        studentPhone: string | null;
        previousSchool: string | null;
        status: import(".prisma/client").$Enums.StudentStatus | null;
        fatherName: string | null;
        fatherPhone: string | null;
        fatherJob: string | null;
        fatherWorkplace: string | null;
        motherName: string | null;
        motherPhone: string | null;
        motherJob: string | null;
        motherWorkplace: string | null;
        hasHealthInsurance: boolean | null;
        healthInsuranceNumber: string | null;
        healthInsuranceStartDate: Date | null;
        healthInsuranceEndDate: Date | null;
        healthInsuranceRegisteredHospital: string | null;
        emergencyContactName: string | null;
        emergencyContactRelationship: string | null;
        emergencyContactPhone: string | null;
        policyCategory: string | null;
        bloodType: string | null;
        allergy: string | null;
        healthNotes: string | null;
        notes: string | null;
        displayOrder: number;
    }>;
    findAll(query: QueryStudentsDto): Promise<import("../common/dto/pagination-query.dto").Paginated<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        schoolYearId: string;
        classId: string;
        fullName: string | null;
        familyAndMiddleName: string | null;
        firstName: string | null;
        dateOfBirth: Date | null;
        gender: import(".prisma/client").$Enums.Gender | null;
        identifier: string | null;
        ethnicity: string | null;
        nationality: string | null;
        address: string | null;
        studentPhone: string | null;
        previousSchool: string | null;
        status: import(".prisma/client").$Enums.StudentStatus | null;
        fatherName: string | null;
        fatherPhone: string | null;
        fatherJob: string | null;
        fatherWorkplace: string | null;
        motherName: string | null;
        motherPhone: string | null;
        motherJob: string | null;
        motherWorkplace: string | null;
        hasHealthInsurance: boolean | null;
        healthInsuranceNumber: string | null;
        healthInsuranceStartDate: Date | null;
        healthInsuranceEndDate: Date | null;
        healthInsuranceRegisteredHospital: string | null;
        emergencyContactName: string | null;
        emergencyContactRelationship: string | null;
        emergencyContactPhone: string | null;
        policyCategory: string | null;
        bloodType: string | null;
        allergy: string | null;
        healthNotes: string | null;
        notes: string | null;
        displayOrder: number;
    }>>;
    bulkUpdate(dto: BulkUpdateStudentsDto): Promise<import("./dto/bulk-update-students.dto").BulkUpdateResult>;
    seedDemo(dto: SeedDemoStudentsDto): Promise<{
        createdCount: number;
    }>;
    reorder(dto: ReorderStudentsDto): Promise<{
        success: true;
    }>;
    findOne(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        schoolYearId: string;
        classId: string;
        fullName: string | null;
        familyAndMiddleName: string | null;
        firstName: string | null;
        dateOfBirth: Date | null;
        gender: import(".prisma/client").$Enums.Gender | null;
        identifier: string | null;
        ethnicity: string | null;
        nationality: string | null;
        address: string | null;
        studentPhone: string | null;
        previousSchool: string | null;
        status: import(".prisma/client").$Enums.StudentStatus | null;
        fatherName: string | null;
        fatherPhone: string | null;
        fatherJob: string | null;
        fatherWorkplace: string | null;
        motherName: string | null;
        motherPhone: string | null;
        motherJob: string | null;
        motherWorkplace: string | null;
        hasHealthInsurance: boolean | null;
        healthInsuranceNumber: string | null;
        healthInsuranceStartDate: Date | null;
        healthInsuranceEndDate: Date | null;
        healthInsuranceRegisteredHospital: string | null;
        emergencyContactName: string | null;
        emergencyContactRelationship: string | null;
        emergencyContactPhone: string | null;
        policyCategory: string | null;
        bloodType: string | null;
        allergy: string | null;
        healthNotes: string | null;
        notes: string | null;
        displayOrder: number;
    }>;
    update(id: string, dto: UpdateStudentDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        schoolYearId: string;
        classId: string;
        fullName: string | null;
        familyAndMiddleName: string | null;
        firstName: string | null;
        dateOfBirth: Date | null;
        gender: import(".prisma/client").$Enums.Gender | null;
        identifier: string | null;
        ethnicity: string | null;
        nationality: string | null;
        address: string | null;
        studentPhone: string | null;
        previousSchool: string | null;
        status: import(".prisma/client").$Enums.StudentStatus | null;
        fatherName: string | null;
        fatherPhone: string | null;
        fatherJob: string | null;
        fatherWorkplace: string | null;
        motherName: string | null;
        motherPhone: string | null;
        motherJob: string | null;
        motherWorkplace: string | null;
        hasHealthInsurance: boolean | null;
        healthInsuranceNumber: string | null;
        healthInsuranceStartDate: Date | null;
        healthInsuranceEndDate: Date | null;
        healthInsuranceRegisteredHospital: string | null;
        emergencyContactName: string | null;
        emergencyContactRelationship: string | null;
        emergencyContactPhone: string | null;
        policyCategory: string | null;
        bloodType: string | null;
        allergy: string | null;
        healthNotes: string | null;
        notes: string | null;
        displayOrder: number;
    }>;
    remove(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        schoolYearId: string;
        classId: string;
        fullName: string | null;
        familyAndMiddleName: string | null;
        firstName: string | null;
        dateOfBirth: Date | null;
        gender: import(".prisma/client").$Enums.Gender | null;
        identifier: string | null;
        ethnicity: string | null;
        nationality: string | null;
        address: string | null;
        studentPhone: string | null;
        previousSchool: string | null;
        status: import(".prisma/client").$Enums.StudentStatus | null;
        fatherName: string | null;
        fatherPhone: string | null;
        fatherJob: string | null;
        fatherWorkplace: string | null;
        motherName: string | null;
        motherPhone: string | null;
        motherJob: string | null;
        motherWorkplace: string | null;
        hasHealthInsurance: boolean | null;
        healthInsuranceNumber: string | null;
        healthInsuranceStartDate: Date | null;
        healthInsuranceEndDate: Date | null;
        healthInsuranceRegisteredHospital: string | null;
        emergencyContactName: string | null;
        emergencyContactRelationship: string | null;
        emergencyContactPhone: string | null;
        policyCategory: string | null;
        bloodType: string | null;
        allergy: string | null;
        healthNotes: string | null;
        notes: string | null;
        displayOrder: number;
    }>;
}
